import Head from "next/head";
import { api } from "~/utils/api";
import {
  SignInButton,
  SignOutButton,
  SignedIn,
  SignedOut,
  useUser,
} from "@clerk/nextjs";
import { LoadingPage, LoadingSpinner } from "~/components/loading";

const CreateFlat = () => {
  const { user } = useUser();

  //const ctx = api.useContext();

  const { mutate, isLoading: isCreating } = api.flat.createFlat.useMutation({
    onSuccess: () => {
      console.log("success");
    },
    onError: (error) => {
      console.log(error);
    },
  });

  const handleCreateFlat = () => {
    mutate();
  };

  if (!user) return null;

  return (
    <button onClick={handleCreateFlat} disabled={isCreating}>
      {isCreating ? <LoadingSpinner size={20} /> : "Create Flat"}
    </button>
  );
};
/**
 * Test code. Needs to be removed.
 */
const ShowFlat = () => {
  const { user } = useUser();

  const { data: userFlat, isLoading } = api.flat.getUserFlatByUserId.useQuery();

  const handleShowFlat = () => {
    // You may want to refresh the data here, or handle it in another way.
  };

  if (!user) return null;

  return (
    <><button onClick={handleShowFlat} disabled={isLoading}>
      {isLoading ? <LoadingSpinner size={20} /> : "Show Flat"}
    </button><div>
        {userFlat && <p>Your flat ID is: {userFlat.flatId}</p>}
      </div></>
  );
};

export default function Home() {
  const { isLoaded: userIsLoaded, isSignedIn } = useUser();

  if (!userIsLoaded) return <LoadingPage />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div>
          <SignedIn>
            <SignOutButton />
            <div>
              <CreateFlat />
            </div>
            <div>
              <ShowFlat />
            </div>
          </SignedIn>
          <SignedOut>
            <SignInButton />
          </SignedOut>
        </div>
      </main>
    </>
  );
}
