import Head from "next/head";
import { useCallback, useState } from "react";
import { api } from "~/utils/api";
import {
  SignIn,
  SignInButton,
  SignOutButton,
  SignedIn,
  SignedOut,
  useUser,
} from "@clerk/nextjs";
import { LoadingPage, LoadingSpinner } from "~/components/loading";

const CreateFlat = () => {
  const { user } = useUser();

  const ctx = api.useContext();

  const { mutate, isLoading: isCreating } = api.flat.createFlat.useMutation({
    onSuccess: () => {
      console.log("success");
    },
    onError: (error) => {
      console.log(error);
    },
  });

  const handleCreateFlat = async () => {
    try {
      await mutate();
    } catch (error) {
      console.log(error);
    }
  };

  if (!user) return null;

  return (
    <button onClick={handleCreateFlat} disabled={isCreating}>
      {isCreating ? <LoadingSpinner size={20} /> : "Create Flat"}
    </button>
  );
};

export default function Home() {
  const { isLoaded: userIsLoaded, isSignedIn } = useUser();

  if (!userIsLoaded) return <LoadingPage />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div>
          <SignedIn>
            <SignOutButton />
            <div>
              <CreateFlat />
            </div>
          </SignedIn>
          <SignedOut>
            <SignInButton />
          </SignedOut>
        </div>
      </main>
    </>
  );
}
